force-app/main/default/objects/Sites__c/Sites__c.object-meta.xml
<CustomObject>
    <label>Sites</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sites__c/fields/BrandUser__c.field-meta.xml
<CustomField>
    <fullName>BrandUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User with brand profile who has access to this site</description>
    <label>Brand User</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select a user with Brand Profile</errorMessage>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Brand Profile</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Brand_User_Sites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sites__c/fields/CorpUser__c.field-meta.xml
<CustomField>
    <fullName>CorpUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Corporate User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sites__c/fields/Primary_Vendor__c.field-meta.xml
<CustomField>
    <fullName>Primary_Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Vendor</label>
    <referenceTo>Vendor__c</referenceTo>
    <relationshipLabel>Sites</relationshipLabel>
    <relationshipName>Sites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Technician__c/Technician__c.object-meta.xml
<CustomObject>
    <label>Technician</label>
    <nameField>
        <label>Technician Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Technicians</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Technician__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Technicians1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Technician__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Vendor__c</referenceTo>
    <relationshipLabel>Technicians</relationshipLabel>
    <relationshipName>Technicians</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trip__c/Trip__c.object-meta.xml
<CustomObject>
    <label>Trip</label>
    <nameField>
        <displayFormat>Trip-{0000}</displayFormat>
        <label>Trip Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trips</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Trip__c/fields/Primary_Technician__c.field-meta.xml
<CustomField>
    <fullName>Primary_Technician__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Technician</label>
    <referenceTo>Technician__c</referenceTo>
    <relationshipLabel>Trips</relationshipLabel>
    <relationshipName>Trips</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Sites__c.field-meta.xml
<CustomField>
    <fullName>Sites__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sites</label>
    <referenceTo>Sites__c</referenceTo>
    <relationshipLabel>Trips</relationshipLabel>
    <relationshipName>Trips</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Trip__c.field-meta.xml
<CustomField>
    <fullName>Trip__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Trip</label>
    <referenceTo>Trip__c</referenceTo>
    <relationshipLabel>Trips</relationshipLabel>
    <relationshipName>Trips</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Vendor__c</referenceTo>
    <relationshipLabel>Trips</relationshipLabel>
    <relationshipName>Trips</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Work_Orders__c.field-meta.xml
<CustomField>
    <fullName>Work_Orders__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Orders</label>
    <referenceTo>Work_Order__c</referenceTo>
    <relationshipLabel>Trips</relationshipLabel>
    <relationshipName>Trips</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vendor__c/Vendor__c.object-meta.xml
<CustomObject>
    <label>Vendor</label>
    <nameField>
        <label>Vendor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendors</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vendor__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Vendors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/Work_Order__c.object-meta.xml
<CustomObject>
    <label>Work Order</label>
    <nameField>
        <displayFormat>WO-{0000}</displayFormat>
        <label>Work Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Order__c/fields/ParentWO__c.field-meta.xml
<CustomField>
    <fullName>ParentWO__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Work Order</label>
    <referenceTo>Work_Order__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Sites__c.field-meta.xml
<CustomField>
    <fullName>Sites__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sites</label>
    <referenceTo>Sites__c</referenceTo>
    <relationshipName>RelatedWO</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Vendor__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TripSharingTriggerHandler.cls
public class TripSharingTriggerHandler {
    public static void handleAfterInsert(List<Trip__c> newTrips) {
        Id CorporateUserId;
        Id BrandUserId;
        List<Trip__c> tripWithRelatedData = [
            SELECT Id, Vendor__c, Vendor__r.User__c, Work_Orders__r.sites__r.CorpUser__c, 
            Work_Orders__r.sites__r.BrandUser__c, CreatedBy.Profile.Name, CreatedById, Primary_Technician__r.User__r.Id 
            FROM Trip__c 
            WHERE Id IN :newTrips
        ];
        
        List<Trip__Share> sharesToCreate = new List<Trip__Share>();
        
        for (Trip__c trip : tripWithRelatedData) {
            CorporateUserId = trip.Work_Orders__r.sites__r.CorpUser__c;
            BrandUserId = trip.Work_Orders__r.sites__r.BrandUser__c;
            
            // Share with brand user
            if (trip.CreatedBy.Profile.Name == 'Vendor Profile') {
                if (trip.Work_Orders__c != null && BrandUserId != null) {
                    sharesToCreate.add(SharingHelper.createTripShare(trip.Id, BrandUserId));
                    
                    // Share with Corporate user
                    if (CorporateUserId != null) {
                        sharesToCreate.add(SharingHelper.createTripShare(trip.Id, CorporateUserId));
                    }
                    
                    // Share with Primary Technician
                    if (trip.Primary_Technician__c != null && trip.Primary_Technician__r.User__r.Id != null) {
                        sharesToCreate.add(SharingHelper.createTripShare(trip.Id, trip.Primary_Technician__r.User__r.Id));
                    }
                }
            }
        }
        
        if (!sharesToCreate.isEmpty()) {
            Database.insert(sharesToCreate, false);
        }
    }
}