force-app/main/default/objects/Brand__c/Brand__c.object-meta.xml
<CustomObject>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Brand__c/fields/Corporate__c.field-meta.xml
<CustomField>
    <fullName>Corporate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Corporate</label>
    <referenceTo>Corporate__c</referenceTo>
    <relationshipLabel>Brands</relationshipLabel>
    <relationshipName>Brands</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Classification__c/Classification__c.object-meta.xml
<CustomObject>
    <label>Classification</label>
    <nameField>
        <label>Classification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classifications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Classification__c/fields/Trade__c.field-meta.xml
<CustomField>
    <fullName>Trade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trade</label>
    <referenceTo>Trade__c</referenceTo>
    <relationshipLabel>Classifications</relationshipLabel>
    <relationshipName>Classifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Corporate__c/Corporate__c.object-meta.xml
<CustomObject>
    <label>Corporate</label>
    <nameField>
        <label>Corporate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Corporates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Issue__c/Issue__c.object-meta.xml
<CustomObject>
    <label>Issue</label>
    <nameField>
        <label>Issue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Issues</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Issue__c/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Classification</label>
    <referenceTo>Classification__c</referenceTo>
    <relationshipLabel>Issues</relationshipLabel>
    <relationshipName>Issues</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sites__c/Sites__c.object-meta.xml
<CustomObject>
    <label>Sites</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sites__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand</label>
    <referenceTo>Brand__c</referenceTo>
    <relationshipLabel>Sites</relationshipLabel>
    <relationshipName>Sites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sites__c/fields/BrandUser__c.field-meta.xml
<CustomField>
    <fullName>BrandUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User with brand profile who has access to this site</description>
    <label>Brand User</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select a user with Brand Profile</errorMessage>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Brand Profile</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Brand_User_Sites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sites__c/fields/Corporate__c.field-meta.xml
<CustomField>
    <fullName>Corporate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Corporate</label>
    <referenceTo>Corporate__c</referenceTo>
    <relationshipLabel>Sites</relationshipLabel>
    <relationshipName>Sites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sites__c/fields/CorpUser__c.field-meta.xml
<CustomField>
    <fullName>CorpUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Corporate User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sites__c/fields/Trade__c.field-meta.xml
<CustomField>
    <fullName>Trade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trade</label>
    <referenceTo>Trade__c</referenceTo>
    <relationshipLabel>Sites</relationshipLabel>
    <relationshipName>Sites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trade__c/Trade__c.object-meta.xml
<CustomObject>
    <label>Trade</label>
    <nameField>
        <label>Trade Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trades</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Trade__c/fields/Corporate__c.field-meta.xml
<CustomField>
    <fullName>Corporate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Corporate</label>
    <referenceTo>Corporate__c</referenceTo>
    <relationshipLabel>Trades</relationshipLabel>
    <relationshipName>Trades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/WorkRequestService.cls
public with sharing class WorkRequestService {

    @AuraEnabled
    public static Id createWorkRequest(Map<String, Object> workOrderRequestData) {
        try {
            System.debug('Starting createWorkRequest method.');

            Work_Order_Request__c workRequest = new Work_Order_Request__c();
            List<Id> userIds = new List<Id>();
            Id currentUserId = UserInfo.getUserId();

            System.debug('Current User ID: ' + currentUserId);

            // Fetch current user details
            User currentUser = [SELECT Id, Name, Profile.Name FROM User WHERE Id = :currentUserId LIMIT 1];
            String profileName = currentUser.Profile.Name;
            String currentUserName = currentUser.Name;

            System.debug('Current User Name: ' + currentUserName);
            System.debug('User Profile Name: ' + profileName);

            workRequest.Status__c = 'In Progress';

            // Set fields from workOrderData
            if (workOrderRequestData.containsKey('Trade__c')) {
                workRequest.Trade__c = (Id)workOrderRequestData.get('Trade__c');
                System.debug('Trade__c: ' + workRequest.Trade__c);
            }

            if (workOrderRequestData.containsKey('Classification__c')) {
                workRequest.Classification__c = (Id)workOrderRequestData.get('Classification__c');
                System.debug('Classification__c: ' + workRequest.Classification__c);
            }

            if (workOrderRequestData.containsKey('Issue__c')) {
                workRequest.Issue__c = (Id)workOrderRequestData.get('Issue__c');
                System.debug('Issue__c: ' + workRequest.Issue__c);
            }

            String siteName = ''; // Initialize to store site name for message
            if (workOrderRequestData.containsKey('Sites__c')) {
                workRequest.Sites__c = (Id)workOrderRequestData.get('Sites__c');

                // Fetch site info to get related users and name
                Sites__c site = [
                    SELECT Name, Corporate__c, Brand__c, BrandUser__c, CorpUser__c
                    FROM Sites__c
                    WHERE Id = :workRequest.Sites__c
                    LIMIT 1
                ];

                siteName = site.Name;

                System.debug('Site Name: ' + siteName);

                // Add users for notification
                if (site.BrandUser__c != null) {
                    userIds.add(site.BrandUser__c);
                    System.debug('Added BrandUser__c: ' + site.BrandUser__c);
                }
                if (site.CorpUser__c != null) {
                    userIds.add(site.CorpUser__c);
                    System.debug('Added CorpUser__c: ' + site.CorpUser__c);
                }
            }

            if (workOrderRequestData.containsKey('Requested_By_Person__c')) {
                workRequest.Request_By_Person__c = (String)workOrderRequestData.get('Requested_By_Person__c');
                System.debug('Requested_By_Person__c: ' + workRequest.Request_By_Person__c);
            }

            if (workOrderRequestData.containsKey('Description__c')) {
                workRequest.Description__c = (String)workOrderRequestData.get('Description__c');
                System.debug('Description__c: ' + workRequest.Description__c);
            }

            // Insert Work Request
            insert workRequest;
            System.debug('Work Order Request inserted with ID: ' + workRequest.Id);

            // Prepare message
            String notificationTitle = 'Work Request Created Successfully';
            String notificationMessage = siteName + ' (Created by ' + currentUserName + ') has created a work request '+ workRequest.Name+' and is asking for approval.';

            // Send notification
            NotificationUtility.sendNotification(
                'Work_Request_Created',
                userIds,
                workRequest.Id,
                notificationTitle,
                notificationMessage
            );

            return workRequest.Id;

        } catch (Exception e) {
            System.debug('Error creating Work Order: ' + e.getMessage());
            throw new AuraHandledException('Error creating Work Order: ' + e.getMessage());
        }
    }
}