force-app/main/default/objects/Brand__c/Brand__c.object-meta.xml
<CustomObject>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Brand__c/fields/Corporate__c.field-meta.xml
<CustomField>
    <fullName>Corporate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Corporate</label>
    <referenceTo>Corporate__c</referenceTo>
    <relationshipLabel>Brands</relationshipLabel>
    <relationshipName>Brands</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Brands</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand_User__c/Brand_User__c.object-meta.xml
<CustomObject>
    <label>Brand User</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Brand User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BrandUsers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Brand_User__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand</label>
    <referenceTo>Brand__c</referenceTo>
    <relationshipLabel>Brand Users</relationshipLabel>
    <relationshipName>BrandUsers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand_User__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>BrandUsers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Corporate__c/Corporate__c.object-meta.xml
<CustomObject>
    <label>Corporate</label>
    <nameField>
        <label>Corporate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Corporates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Corporate__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Corporate Profile</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Corporates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Estimate__c/Estimate__c.object-meta.xml
<CustomObject>
    <label>Estimate</label>
    <nameField>
        <label>Estimate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estimates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Estimate__c/fields/Estimate_Date__c.field-meta.xml
<CustomField>
    <fullName>Estimate_Date__c</fullName>
    <label>Estimate Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Estimate__c/fields/Grand_total__c.field-meta.xml
<CustomField>
    <fullName>Grand_total__c</fullName>
    <formula>total_amount__c  +  Tax__c  -  Discount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Grand total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Estimate__c/fields/Incurred_Data__c.field-meta.xml
<CustomField>
    <fullName>Incurred_Data__c</fullName>
    <label>Incurred Data</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Estimate__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Estimate__c/fields/Work_Orders__c.field-meta.xml
<CustomField>
    <fullName>Work_Orders__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Orders</label>
    <referenceTo>Work_Order__c</referenceTo>
    <relationshipLabel>Estimates</relationshipLabel>
    <relationshipName>Estimates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoices</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Invoices Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Estimate__c.field-meta.xml
<CustomField>
    <fullName>Estimate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estimate</label>
    <referenceTo>Estimate__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Work_Orders__c.field-meta.xml
<CustomField>
    <fullName>Work_Orders__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Orders</label>
    <referenceTo>Work_Order__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sites__c/Sites__c.object-meta.xml
<CustomObject>
    <label>Sites</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sites__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand</label>
    <referenceTo>Brand__c</referenceTo>
    <relationshipLabel>Sites</relationshipLabel>
    <relationshipName>Sites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sites__c/fields/BrandUser__c.field-meta.xml
<CustomField>
    <fullName>BrandUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User with brand profile who has access to this site</description>
    <label>Brand User</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select a user with Brand Profile</errorMessage>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Brand Profile</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Brand_User_Sites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sites__c/fields/Corporate__c.field-meta.xml
<CustomField>
    <fullName>Corporate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Corporate</label>
    <referenceTo>Corporate__c</referenceTo>
    <relationshipLabel>Sites</relationshipLabel>
    <relationshipName>Sites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sites__c/fields/CorpUser__c.field-meta.xml
<CustomField>
    <fullName>CorpUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Corporate User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sites__c/fields/Estimate__c.field-meta.xml
<CustomField>
    <fullName>Estimate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estimate</label>
    <referenceTo>Estimate__c</referenceTo>
    <relationshipLabel>Sites</relationshipLabel>
    <relationshipName>Sites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vendor__c/Vendor__c.object-meta.xml
<CustomObject>
    <label>Vendor</label>
    <nameField>
        <label>Vendor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendors</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vendor__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vendor__c/fields/Estimate__c.field-meta.xml
<CustomField>
    <fullName>Estimate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estimate</label>
    <referenceTo>Estimate__c</referenceTo>
    <relationshipLabel>Vendors</relationshipLabel>
    <relationshipName>Vendors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vendor__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Pending Documentation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vendor__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Vendors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/Work_Order__c.object-meta.xml
<CustomObject>
    <label>Work Order</label>
    <nameField>
        <displayFormat>WO-{0000}</displayFormat>
        <label>Work Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Order__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand</label>
    <referenceTo>Brand__c</referenceTo>
    <relationshipName>RelatedWO</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Corporate__c.field-meta.xml
<CustomField>
    <fullName>Corporate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Corporate</label>
    <referenceTo>Corporate__c</referenceTo>
    <relationshipName>RelatedWO</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Estimate_Data__c.field-meta.xml
<CustomField>
    <fullName>Estimate_Data__c</fullName>
    <label>Estimate Data</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Sites__c.field-meta.xml
<CustomField>
    <fullName>Sites__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sites</label>
    <referenceTo>Sites__c</referenceTo>
    <relationshipName>RelatedWO</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
            <value>
                <fullName>Cannot Complete</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Recurring</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Request Declined</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending Vendor Approval</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
                <isActive>false</isActive>
                <label>Assigned</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/testdummy.cls
public with sharing class InvoiceApprovalController {
    @AuraEnabled
    public static string submitInvoiceForApproval(Id invoiceId){
        try {
            

            Invoice__c invoice = [SELECT Id,Work_Orders__c,Status__c FROM Invoice__c WHERE Id =:invoiceId];
            
            Work_Order__c woList = [
                SELECT Id, Brand__c, Corporate__c ,Sites__c
                FROM Work_Order__c 
                WHERE Id = :invoice.Work_Orders__c 
                LIMIT 1
            ];

            List<Id> userIds = new LIst<Id>();

        if (workOrder.Sites__c != null){
        Sites__c siteUsers = [
                SELECT CorpUser__c,BrandUser__c
                FROM Sites__c 
                WHERE Id = :woList.Sites__c 
            ];
        

        // Step 3: Fetch Brand Users
        if (siteUsers.BrandUser__c != null) {
           
                userIds.add(siteUsers.BrandUser__c);
                userIds.add(siteUsers.CorpUser__c);
            }
        }

        invoice.Status__c='On Hold';
        update Invoice;

List<Invoice__Share> shares = new List<Invoice__Share>();
for (Id uid : userIds) {
    Invoice__Share es = new Invoice__Share(
        ParentId = invoiceId,
        UserOrGroupId = uid,
        AccessLevel = 'Edit',
        RowCause = Schema.Estimate__Share.RowCause.Manual
    );
    System.debug('Prepared share record: ' + es);
    shares.add(es);
}

if (!shares.isEmpty()) {
    insert shares;
    System.debug('Inserted share records: ' + shares);
}

        String body = ' Invoice has been Submitted for Approval' ;
        String title = 'Invoice Approval' ;
        
        
        List<Id> userIdList = new List<Id>(userIds);
        
        NotificationUtility.sendNotification('InvoiceApproval',  userIds,  invoice.Id ,body,title);

        return 'Success: Invoice Submitted for Approval';

        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }


    @AuraEnabled
    public static String createInvoiceFromEstimate(Id estimateId) {
    

        try {
            if (String.isBlank(estimateId)) {
                throw new AuraHandledException('Estimate Id is required.');
            }

            // Step 1: Fetch the Estimate
            List<Estimate__c> estimateList = [
                SELECT Id, Work_Orders__c, Status__c , Estimate_Data__c, Incurred_Data__c, Email__c,	Estimate_Date__c,	Grand_total__c,Net_Total__c,	Tax_Amount__c,
                Value__c,	Description__c,Account__c , netPrice__c , grandTotal__c , totalDiscount__c  , Internal_Estimate_No__c ,Assessment_Troubleshoot__c ,
                Proposal_For_Repairs__c
                FROM Estimate__c 
                WHERE Id = :estimateId
                LIMIT 1
            ];

            if (estimateList.isEmpty()) {
                return 'Error: Estimate not found.';
            }

            Estimate__c estimate = estimateList[0];

            if (estimate.Status__c == 'Pending' ) {
                return ' Waiting For Estimate Approval';
            }
            

        


            // Create Invoice
        Invoice__c invoice = new Invoice__c();
        
        invoice.Estimate__c=estimateid;
invoice.Work_Orders__c     = estimate.Work_Orders__c;
invoice.Status__c          = 'Pending';
invoice.Estimate_Data__c   = estimate.Estimate_Data__c;
invoice.Incurred_Data__c   = estimate.Incurred_Data__c;
invoice.Email__c           = estimate.Email__c;
invoice.Estimate_Date__c   = estimate.Estimate_Date__c;
// invoice.Grand_total__c     = estimate.Grand_total__c;
// invoice.Net_Total__c       = estimate.Net_Total__c;
invoice.Tax_Amount__c      = estimate.Tax_Amount__c;
invoice.Value__c           = estimate.Value__c;
invoice.Description__c     = estimate.Description__c;
invoice.Account__c         = estimate.Account__c;
invoice.netTotal__c         = estimate.netPrice__c;
invoice.grandTotal__c         = estimate.grandTotal__c;
invoice.totalDiscount__c         = estimate.totalDiscount__c;
invoice.Assessment_Troubleshoot__c = estimate.Assessment_Troubleshoot__c;
invoice.Proposal_For_Repairs__c = estimate.Proposal_For_Repairs__c;
invoice.Internal_Estimate_No__c = estimate.Internal_Estimate_No__c;

        insert invoice;

            // Step 2: Fetch related Work Order
            if (invoice.Work_Orders__c == null) {
                return 'Error: Estimate has no associated Work Order.';
            }

        List<Work_Order__c> woList = [
            SELECT Id, Brand__c, Corporate__c ,Sites__c
            FROM Work_Order__c 
            WHERE Id = :invoice.Work_Orders__c 
            LIMIT 1
        ];

        if (woList.isEmpty()) {
            return 'Error: Work Order not found.';
        }

        Work_Order__c workOrder = woList[0];

        Set<Id> userIds = new Set<Id>();

        if (workOrder.Sites__c != null){
        Sites__c siteUsers = [
                SELECT CorpUser__c,BrandUser__c
                FROM Sites__c 
                WHERE Id = :workOrder.Sites__c 
            ];
        

        // Step 3: Fetch Brand Users
        if (siteUsers.BrandUser__c != null) {
           
                userIds.add(siteUsers.BrandUser__c);
                userIds.add(siteUsers.CorpUser__c);
            }
        }

      //System.debug("Site"+ " Brand: "  + siteUsers.BrandUser__r.Name + " Corp :" + siteUsers.corpUser__c);

      
            List<Invoice__Share> shares = new List<Invoice__Share>();
            for (Id uid : userIds) {
                Invoice__Share es = new Invoice__Share(
                    ParentId = invoice.Id,
                    UserOrGroupId = uid,
                    AccessLevel = 'Edit',
                    RowCause = Schema.Estimate__Share.RowCause.Manual
                );
                System.debug('Prepared share record: ' + es);
                shares.add(es);
            }
        
            if (!shares.isEmpty()) {
                insert shares;
            }

            String body = ' Invoice has been Submitted for Approval' ;
            String title = 'Invoice Approval' ;
            
            
            List<Id> userIdList = new List<Id>(userIds);
            
            NotificationUtility.sendNotification('InvoiceApproval',  userIdList,  invoice.Id ,body,title);
            Id invoiceId=invoice.Id;
    return invoiceId;

        } catch (Exception e) {
            throw new AuraHandledException('Error: ' + e.getMessage());
        }
    }


    @AuraEnabled(cacheable=true)
    public static String getCurrentUserProfileName() {
        try {
            User u = [SELECT Profile.Name FROM User WHERE Id = :UserInfo.getUserId()];
            return u.Profile.Name;
        } catch (Exception e) {
            return null;
        }
    }

    @AuraEnabled
    public static String updateInvoiceStatus(Id invoiceId, String action) {
        System.debug('invoiceId: ' + invoiceId + ', action: ' + action);
    
        Invoice__c invoice = [SELECT Id, Status__c,Work_Orders__c FROM Invoice__c WHERE Id = :invoiceId LIMIT 1];
    
       
            System.debug('Current Status: ' + invoice.Status__c);
            if (invoice.Status__c == 'Pending' || invoice.Status__c=='On Hold') {
                if (action == 'approve') {
                    invoice.Status__c = 'Approved';
                } else if (action == 'reject') {
                    invoice.Status__c = 'Rejected';
                }
                update invoice;
            } else {
                System.debug('Status is not Submitted, skipping update.');
            }
        


            List<Id> userIdList = new List<Id>();

        Invoice__c est = [Select CreatedById from Invoice__c where Id =:invoiceId];

        User u = [SELECT Id,Profile.Name FROM User WHERE Id = :est.CreatedById LIMIT 1];

        if(u.Profile.Name=='Vendor Profile' || u.Profile.Name=='System Administrator'){

            userIdList.add(u.Id);
        }

            // if (invoice.Work_Orders__c == null) {
            //     return 'Error: Estimate has no associated Work Order.';
            // }

            // List<Work_Order__c> woList = [
            //     SELECT Id,Vendor__c
            //     FROM Work_Order__c 
            //     WHERE Id = :invoice.Work_Orders__c 
            //     LIMIT 1
            // ];

            // if (woList.isEmpty()) {
            //     return 'Error: Work Order not found.';
            // }

            // Work_Order__c workOrder = woList[0];

            // Set<Id> userIds = new Set<Id>();

            // // Step 3: Fetch Brand Users
            // if (workOrder.Brand__c != null) {
            //     List<Brand_User__c> brandUsers = [
            //         SELECT User__c 
            //         FROM Brand_User__c 
            //         WHERE Brand__c = :workOrder.Brand__c AND User__c != null
            //     ];
            //     for (Brand_User__c bu : brandUsers) {
            //         userIds.add(bu.User__c);
            //     }
            // }

            // Step 4: Fetch Vendor User
            // if (workOrder.Vendor__c != null) {
            //     List<Vendor__c> vendorList = [
            //         SELECT User__c 
            //         FROM Vendor__c 
            //         WHERE Id = :workOrder.Vendor__c 
            //         LIMIT 1
            //     ];
            //     if (!vendorList.isEmpty() && vendorList[0].User__c != null) {
            //         userIds.add(vendorList[0].User__c);
            //     }
            // }

System.debug('userIds: ' + userIdList);
            


             // Step 6: Send notification
// Id notifTypeId = [
//     SELECT Id 
//     FROM CustomNotificationType 
//     WHERE DeveloperName = 'EstimateApproval' 
//     LIMIT 1
// ].Id;

// Messaging.CustomNotification notification = new Messaging.CustomNotification();
// notification.setTitle('Invoice ' + invoice.Status__c);
// notification.setBody(' Invoice has been ' +  invoice.Status__c);
// notification.setSenderId(UserInfo.getUserId());
// notification.setNotificationTypeId(notifTypeId);
// notification.setTargetId(invoice.Id); // Clicking opens Estimate

// // Convert to Set<String>
// Set<String> userIdStrings = new Set<String>();
// for (Id uid : userIds) {
//     userIdStrings.add(String.valueOf(uid));
// }

// // Send notification
// notification.send(userIdStrings);
String body = ' Invoice has been ' +  invoice.Status__c ;
String title = 'Invoice ' + invoice.Status__c;


NotificationUtility.sendNotification('InvoiceApproval',  userIdList,  invoice.Id ,body,title);

           
    
        return 'Success: Invoice Finalized';


    }
}