force-app/main/default/objects/Brand__c/Brand__c.object-meta.xml
<CustomObject>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Brand__c/fields/Corporate__c.field-meta.xml
<CustomField>
    <fullName>Corporate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Corporate</label>
    <referenceTo>Corporate__c</referenceTo>
    <relationshipLabel>Brands</relationshipLabel>
    <relationshipName>Brands</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Brands</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Corporate__c/Corporate__c.object-meta.xml
<CustomObject>
    <label>Corporate</label>
    <nameField>
        <label>Corporate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Corporates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Corporate__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Corporate Profile</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Corporates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Estimate__c/Estimate__c.object-meta.xml
<CustomObject>
    <label>Estimate</label>
    <nameField>
        <label>Estimate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estimates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Estimate__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <displayFormat>E-{0000}</displayFormat>
    <label>Name</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Estimate__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Estimate__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <formula>($User.FirstName) + ($User.LastName)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Related Vendor</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Estimate__c/fields/Work_Orders__c.field-meta.xml
<CustomField>
    <fullName>Work_Orders__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Orders</label>
    <referenceTo>Work_Order__c</referenceTo>
    <relationshipLabel>Estimates</relationshipLabel>
    <relationshipName>Estimates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sites__c/Sites__c.object-meta.xml
<CustomObject>
    <label>Sites</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sites__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand</label>
    <referenceTo>Brand__c</referenceTo>
    <relationshipLabel>Sites</relationshipLabel>
    <relationshipName>Sites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sites__c/fields/BrandUser__c.field-meta.xml
<CustomField>
    <fullName>BrandUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User with brand profile who has access to this site</description>
    <label>Brand User</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select a user with Brand Profile</errorMessage>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Brand Profile</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Brand_User_Sites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sites__c/fields/Corporate__c.field-meta.xml
<CustomField>
    <fullName>Corporate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Corporate</label>
    <referenceTo>Corporate__c</referenceTo>
    <relationshipLabel>Sites</relationshipLabel>
    <relationshipName>Sites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sites__c/fields/CorpUser__c.field-meta.xml
<CustomField>
    <fullName>CorpUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Corporate User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sites__c/fields/Estimate__c.field-meta.xml
<CustomField>
    <fullName>Estimate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estimate</label>
    <referenceTo>Estimate__c</referenceTo>
    <relationshipLabel>Sites</relationshipLabel>
    <relationshipName>Sites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vendor__c/Vendor__c.object-meta.xml
<CustomObject>
    <label>Vendor</label>
    <nameField>
        <label>Vendor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendors</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vendor__c/fields/Estimate__c.field-meta.xml
<CustomField>
    <fullName>Estimate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estimate</label>
    <referenceTo>Estimate__c</referenceTo>
    <relationshipLabel>Vendors</relationshipLabel>
    <relationshipName>Vendors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vendor__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Pending Documentation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vendor__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Vendors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/Work_Order__c.object-meta.xml
<CustomObject>
    <label>Work Order</label>
    <nameField>
        <displayFormat>WO-{0000}</displayFormat>
        <label>Work Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Order__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand</label>
    <referenceTo>Brand__c</referenceTo>
    <relationshipName>RelatedWO</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Corporate__c.field-meta.xml
<CustomField>
    <fullName>Corporate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Corporate</label>
    <referenceTo>Corporate__c</referenceTo>
    <relationshipName>RelatedWO</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Sites__c.field-meta.xml
<CustomField>
    <fullName>Sites__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sites</label>
    <referenceTo>Sites__c</referenceTo>
    <relationshipName>RelatedWO</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
            <value>
                <fullName>Cannot Complete</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Recurring</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Request Declined</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending Vendor Approval</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
                <isActive>false</isActive>
                <label>Assigned</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Vendor__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EstimateApprovalController.cls
public with sharing class EstimateApprovalController {
    @AuraEnabled
    public static String submitForApproval(Id estimateId) {
        try {
            if (String.isBlank(estimateId)) {
                throw new AuraHandledException('Estimate Id is required.');
            }

            // Step 1: Fetch the Estimate
            List<Estimate__c> estimateList = [
                SELECT Id, Work_Orders__c, Status__c,Name__c 
                FROM Estimate__c 
                WHERE Id = :estimateId
                LIMIT 1
            ];

            if (estimateList.isEmpty()) {
                return 'Error: Estimate not found.';
            }

            Estimate__c estimate = estimateList[0];

            // Check status
            if (estimate.Status__c == 'Approved' || estimate.Status__c == 'Rejected') {
                return 'Estimate already finalized.';
            }

            // Step 2: Fetch related Work Order
            if (estimate.Work_Orders__c == null) {
                return 'Error: Estimate has no associated Work Order.';
            }

            List<Work_Order__c> woList = [
                SELECT Id, Brand__c, Corporate__c ,Sites__c,Vendor__c,Status__c
                FROM Work_Order__c 
                WHERE Id = :estimate.Work_Orders__c 
                LIMIT 1
            ];

            if (woList.isEmpty()) {
                return 'Error: Work Order not found.';
            }

            Work_Order__c workOrder = woList[0];

         //   WorkOrderStatusFunction.checkWithWOStatus(workOrder.Id);

            Vendor__c v =[Select Name from Vendor__c where Id=:workOrder.Vendor__c];
            
            
            Set<Id> userIds = new Set<Id>();

            // Step 3: Fetch Brand Users
            if (workOrder.Sites__c != null){
                Sites__c siteUsers = [
                        SELECT CorpUser__c,BrandUser__c
                        FROM Sites__c 
                        WHERE Id = :workOrder.Sites__c 
                    ];
                
        
                // Step 3: Fetch Brand Users
                if (siteUsers.BrandUser__c != null) {
                   
                        userIds.add(siteUsers.BrandUser__c);
                        userIds.add(siteUsers.CorpUser__c);
                    }


                System.debug('@@@ siteUsers.CorpUser__c'+siteUsers.CorpUser__c);
                System.debug('@@@ siteUsers.CorpUser__c'+siteUsers.BrandUser__c);
                }
        

            // Step 5: Share Estimate__c record
            System.debug('Sharing Estimate with users: ' + userIds);

List<Estimate__Share> shares = new List<Estimate__Share>();
for (Id uid : userIds) {
    Estimate__Share es = new Estimate__Share(
        ParentId = estimate.Id,
        UserOrGroupId = uid,
        AccessLevel = 'Edit',
        RowCause = Schema.Estimate__Share.RowCause.Manual
    );
    System.debug('Prepared share record: ' + es);
    shares.add(es);
}

if (!shares.isEmpty()) {
    insert shares;
    System.debug('Inserted share records: ' + shares);
}

 String  body = ' New Estimate '+ estimate.Name__c +' has been Submitted for Approval by '+ v.Name ;
String  title = 'New Estimate has be sent for Approval' ;


List<Id> userIdList = new List<Id>(userIds);

NotificationUtility.sendNotification('EstimateApproval',  userIdList,  estimate.Id ,body,title);

               
            // Step 6: Update status
            estimate.Status__c = 'Submited_For_Approval';
            
            update estimate;
            

            return 'Success: Estimate submitted for approval.';

        } catch (Exception e) {
            throw new AuraHandledException('Error: ' + e.getMessage());
        }
    }

// this is a button apex controller // i want that as soon as this controller is accessed a notification is sent to the users fetched from above // use customnotification / messaging




    @AuraEnabled(cacheable=true)
    public static String getCurrentUserProfileName() {
        try {
            User u = [SELECT Profile.Name FROM User WHERE Id = :UserInfo.getUserId()];
            return u.Profile.Name;
        } catch (Exception e) {
            return null;
        }
    }

    @AuraEnabled
    public static String updateEstimateStatus(Id estimateId, String action) {
        System.debug('estimateId: ' + estimateId + ', action: ' + action);
    
        Estimate__c estimate = [SELECT Id, Status__c,Name__c, Work_Orders__c FROM Estimate__c WHERE Id = :estimateId LIMIT 1];
    	
        if (estimate != null) {
            System.debug('Current Status: ' + estimate.Status__c);
            if (estimate.Status__c == 'Pending' || estimate.Status__c == 'Submited_For_Approval') 
                 {
                if (action == 'approve') {
                    estimate.Status__c = 'Approved';
                } else if (action == 'reject') {
                    estimate.Status__c = 'Rejected';
                }
                update estimate;
            } else {
                System.debug('Status is not Submitted, skipping update.');
            }
        }


        List<Id> userIdList = new List<Id>();

        Estimate__c est = [Select CreatedById from Estimate__c where Id =:estimateId];

        User u = [SELECT Id,Profile.Name FROM User WHERE Id = :est.CreatedById LIMIT 1];

        if(u.Profile.Name=='Vendor Profile' || u.Profile.Name=='System Administrator'){

            userIdList.add(u.Id);
        }


                   // Step 1: Fetch the Estimate
                //    List<Estimate__c> estimateList = [
                //     SELECT Id, Work_Orders__c, Status__c 
                //     FROM Estimate__c 
                //     WHERE Id = :estimateId
                //     LIMIT 1
                // ];
    
                // if (estimateList.isEmpty()) {
                //     return 'Error: Estimate not found.';
                // }
    
                // Estimate__c estimate1 = estimateList[0];
    
                // Check status
                // if (estimate.Status__c == 'Approved' || estimate.Status__c == 'Rejected') {
                //     return 'Estimate already finalized.';
                // }
    
                // Step 2: Fetch related Work Order
                if (estimate.Work_Orders__c == null) {
                    return 'Error: Estimate has no associated Work Order.';
                }
    
                List<Work_Order__c> woList = [
                    SELECT Id,Vendor__c
                    FROM Work_Order__c 
                    WHERE Id = :estimate.Work_Orders__c 
                    LIMIT 1
                ];
    
                if (woList.isEmpty()) {
                    return 'Error: Work Order not found.';
                }
    
                Work_Order__c workOrder = woList[0];

               // WorkOrderStatusFunction.checkWithWOStatus(workOrder.Id);
    
                // Set<Id> userIds = new Set<Id>();
    
                
    
                // // Step 4: Fetch Vendor User
                // if (workOrder.Vendor__c != null) {
                //     List<Vendor__c> vendorList = [
                //         SELECT User__c 
                //         FROM Vendor__c 
                //         WHERE Id = :workOrder.Vendor__c 
                //         LIMIT 1
                //     ];
                //     if (!vendorList.isEmpty() && vendorList[0].User__c != null) {
                //         userIds.add(vendorList[0].User__c);
                //     }
                // }

              
System.debug('userLIst '+userIdList);


                String  body= ' Estimate ' + estimate.Name__c +' has been ' +  estimate.Status__c +' by '+ UserInfo.getName();
String title= 'Estimate has been ' + estimate.Status__c;




NotificationUtility.sendNotification('EstimateApproval',  userIdList,  estimate.Id ,body,title);
               
        
            return 'Success: Estimate Finalized';





    }
    
}