force-app/main/default/objects/Brand__c/Brand__c.object-meta.xml
<CustomObject>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Brand__c/fields/BrandOwner__c.field-meta.xml
<CustomField>
    <fullName>BrandOwner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>associateBrandUser</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand__c/fields/Corporate__c.field-meta.xml
<CustomField>
    <fullName>Corporate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Corporate</label>
    <referenceTo>Corporate__c</referenceTo>
    <relationshipLabel>Brands</relationshipLabel>
    <relationshipName>Brands</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand__c/fields/CorporateUser__c.field-meta.xml
<CustomField>
    <fullName>CorporateUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Corporate Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>associateBrand</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Brands</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Corporate__c/Corporate__c.object-meta.xml
<CustomObject>
    <label>Corporate</label>
    <nameField>
        <label>Corporate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Corporates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Corporate__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Corporate Profile</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Corporates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sites__c/Sites__c.object-meta.xml
<CustomObject>
    <label>Sites</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sites__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand</label>
    <referenceTo>Brand__c</referenceTo>
    <relationshipLabel>Sites</relationshipLabel>
    <relationshipName>Sites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sites__c/fields/BrandUser__c.field-meta.xml
<CustomField>
    <fullName>BrandUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User with brand profile who has access to this site</description>
    <label>Brand User</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select a user with Brand Profile</errorMessage>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Brand Profile</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Brand_User_Sites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sites__c/fields/Corporate__c.field-meta.xml
<CustomField>
    <fullName>Corporate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Corporate</label>
    <referenceTo>Corporate__c</referenceTo>
    <relationshipLabel>Sites</relationshipLabel>
    <relationshipName>Sites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sites__c/fields/CorpUser__c.field-meta.xml
<CustomField>
    <fullName>CorpUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Corporate User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sites__c/fields/Site_User__c.field-meta.xml
<CustomField>
    <fullName>Site_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User with site user profile who has access to this site</description>
    <label>Site User</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select a user with Site Profile</errorMessage>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Site Profile</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Site_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SitesTriggerHandler.cls
public class SitesTriggerHandler {
    public static void handleAfterInsert(List<Sites__c> newSites) {
        // Query Sites with related Brand and Users
        List<Sites__c> sitesWithRelatedData = [
            SELECT Id, Brand__c, BrandUser__c, Site_User__c, Corporate__c,
                   Brand__r.CorporateUser__c,Brand__r.BrandOwner__c, Corporate__r.User__c,
                   CreatedBy.Profile.Name, CreatedById
            FROM Sites__c 
            WHERE Id IN :newSites
        ];
        
        List<Sites__Share> sharesToCreate = new List<Sites__Share>();
        List<Sites__c> sitesToUpdate = new List<Sites__c>();
        
        for(Sites__c site : sitesWithRelatedData) {
            Sites__c siteToUpdate = new Sites__c(Id = site.Id);
            
            // Corporate Profile user creating record
            if(site.CreatedBy.Profile.Name == 'Corporate Profile') {
                // Update corporate user with current logged in user
                siteToUpdate.CorpUser__c = site.CreatedById;
                sitesToUpdate.add(siteToUpdate);
                
                // Share with Brand User from Brand
                if(site.Brand__c != null && site.Brand__r.brandOwner__c != null) {
                    sharesToCreate.add(SharingHelper.createSiteShare(site.Id, site.Brand__r.brandOwner__c));
                }
                
                // Share with Site User
                if(site.Site_User__c != null) {
                    sharesToCreate.add(SharingHelper.createSiteShare(site.Id, site.Site_User__c));
                }
            }
            // Brand Profile user creating record
            else if(site.CreatedBy.Profile.Name == 'Brand Profile') {
                // Update brand user with current logged in user
                siteToUpdate.BrandUser__c = site.CreatedById;
                sitesToUpdate.add(siteToUpdate);
                
                // Share with Corporate User from Corporate
                if(site.Corporate__c != null && site.Corporate__r.User__c != null) {
                    sharesToCreate.add(SharingHelper.createSiteShare(site.Id, site.Corporate__r.User__c));
                }
                
                // Share with Site User
                if(site.Site_User__c != null) {
                    sharesToCreate.add(SharingHelper.createSiteShare(site.Id, site.Site_User__c));
                }
            }
        }
        
        if(!sitesToUpdate.isEmpty()) {
            update sitesToUpdate;
        }
        
        if(!sharesToCreate.isEmpty()) {
            Database.insert(sharesToCreate, false);
        }
    }
}