force-app/main/default/objects/Corporate__c/Corporate__c.object-meta.xml
<CustomObject>
    <label>Corporate</label>
    <nameField>
        <label>Corporate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Corporates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sites__c/Sites__c.object-meta.xml
<CustomObject>
    <label>Sites</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sites__c/fields/Corporate__c.field-meta.xml
<CustomField>
    <fullName>Corporate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Corporate</label>
    <referenceTo>Corporate__c</referenceTo>
    <relationshipLabel>Sites</relationshipLabel>
    <relationshipName>Sites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sites__c/fields/Site_User__c.field-meta.xml
<CustomField>
    <fullName>Site_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User with site user profile who has access to this site</description>
    <label>Site User</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select a user with Site Profile</errorMessage>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Site Profile</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Site_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sites__c/fields/Trade__c.field-meta.xml
<CustomField>
    <fullName>Trade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trade</label>
    <referenceTo>Trade__c</referenceTo>
    <relationshipLabel>Sites</relationshipLabel>
    <relationshipName>Sites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trade__c/Trade__c.object-meta.xml
<CustomObject>
    <label>Trade</label>
    <nameField>
        <label>Trade Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trades</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Trade__c/fields/Corporate__c.field-meta.xml
<CustomField>
    <fullName>Corporate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Corporate</label>
    <referenceTo>Corporate__c</referenceTo>
    <relationshipLabel>Trades</relationshipLabel>
    <relationshipName>Trades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TradeLookupController.cls
public class TradeLookupController {
    
    @AuraEnabled(cacheable=true)
    public static List<Trade__c> getFilteredTrades(Id workOrderId, String userProfile) {
        Id corporateId = null;
        
        if (userProfile == 'FM - Site User') {
            Sites__c userSite = [SELECT Corporate__r.Id FROM Sites__c WHERE Site_User__c = :UserInfo.getUserId() LIMIT 1];
            corporateId = userSite.Corporate__r.Id;
        } else if (userProfile == 'System Administrator') {
            if (workOrderId != null) {
                WorkOrder workOrders = [SELECT Corporate__c FROM workOrder WHERE Id = :workOrderId LIMIT 1];
                corporateId = workOrders.Corporate__c;
            }
        }
        
        List<Trade__c> filteredTrades = [SELECT Id, Name FROM Trade__c WHERE Corporate__r.Id = :corporateId];
        return filteredTrades;
    }
}