force-app/main/default/objects/Classification__c/Classification__c.object-meta.xml
<CustomObject>
    <label>Classification</label>
    <nameField>
        <label>Classification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classifications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Estimate__c/Estimate__c.object-meta.xml
<CustomObject>
    <label>Estimate</label>
    <nameField>
        <label>Estimate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estimates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Estimate__c/fields/Grand_Total_amount__c.field-meta.xml
<CustomField>
    <fullName>Grand_Total_amount__c</fullName>
    <formula>Net_Total__c    +    Total_Discount__c  +  Tax_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Grand Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Estimate__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Estimate__c/fields/Work_Orders__c.field-meta.xml
<CustomField>
    <fullName>Work_Orders__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Orders</label>
    <referenceTo>Work_Order__c</referenceTo>
    <relationshipLabel>Estimates</relationshipLabel>
    <relationshipName>Estimates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Issue__c/Issue__c.object-meta.xml
<CustomObject>
    <label>Issue</label>
    <nameField>
        <label>Issue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Issues</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Labor__c/Labor__c.object-meta.xml
<CustomObject>
    <label>Labor</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>Labor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Labors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Labor__c/fields/Estimates__c.field-meta.xml
<CustomField>
    <fullName>Estimates__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estimate</label>
    <referenceTo>Estimate__c</referenceTo>
    <relationshipLabel>Labors (Estimate)</relationshipLabel>
    <relationshipName>Labors1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Labor__c/fields/Net_Price__c.field-meta.xml
<CustomField>
    <fullName>Net_Price__c</fullName>
    <formula>Quantity__c  *  Technician_Quantity__c  *  Unit_Price__c</formula>
    <label>Net Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Labor__c/fields/Technician_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Technician_Quantity__c</fullName>
    <label>Technician Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Labor__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Incurred for Estimate</fullName>
            </value>
            <value>
                <fullName>Estimate</fullName>
            </value>
            <value>
                <fullName>Incurred for Invoice</fullName>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Labor__c/recordTypes/Estimate.recordType-meta.xml
<RecordType>
    <fullName>Estimate</fullName>
    <active>true</active>
    <label>Estimate</label>
</RecordType>

force-app/main/default/objects/Trade__c/Trade__c.object-meta.xml
<CustomObject>
    <label>Trade</label>
    <nameField>
        <label>Trade Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trades</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Order__c/Work_Order__c.object-meta.xml
<CustomObject>
    <label>Work Order</label>
    <nameField>
        <displayFormat>WO-{0000}</displayFormat>
        <label>Work Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Order__c/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Classification</label>
    <referenceTo>Classification__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Issue__c.field-meta.xml
<CustomField>
    <fullName>Issue__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Issue</label>
    <referenceTo>Issue__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/ParentWO__c.field-meta.xml
<CustomField>
    <fullName>ParentWO__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Work Order</label>
    <referenceTo>Work_Order__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
            <value>
                <fullName>Cannot Complete</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Recurring</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Request Declined</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending Vendor Approval</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
                <isActive>false</isActive>
                <label>Assigned</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Trade__c.field-meta.xml
<CustomField>
    <fullName>Trade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trade</label>
    <referenceTo>Trade__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/WorkOrderNumber__c.field-meta.xml
<CustomField>
    <fullName>WorkOrderNumber__c</fullName>
    <displayFormat>A-{0000}</displayFormat>
    <label>WorkOrderNumber</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/classes/EstimateController1.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 03-03-2025
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public class EstimateController1 {
    public Estimate__c estimate { get; private set; }
    public List<Labor__c> incurredLabor { get; private set; }
    public List<Labor__c> estimateLabor { get; private set; }

    public EstimateController1(ApexPages.StandardController stdController) {
        this.estimate = [SELECT Id, Name, Status__c,  
                             Tax_Amount__c, Grand_Total_amount__c,
                                 Proposal_For_Repairs__c,
                                Work_Orders__r.Trade__r.Name, 
                                Work_Orders__r.Classification__r.Name, 
                                Work_Orders__r.Issue__r.Name,
                                Work_Orders__r.WorkOrderNumber__c
                         FROM Estimate__c
                         WHERE Id = :stdController.getId()];

        // Fetch related Labor records based on Type and Record Type
        incurredLabor = [SELECT Quantity__c, Technician_Quantity__c, Details__c, Unit_Price__c, Net_Price__c 
                         FROM Labor__c 
                         WHERE Estimates__c = :estimate.Id AND Type__c = 'Incurred for Estimate'];

        estimateLabor = [SELECT Quantity__c, Technician_Quantity__c, Details__c, Unit_Price__c, Net_Price__c 
                         FROM Labor__c 
                         WHERE Estimates__c = :estimate.Id AND Type__c = 'Estimate'];
    }
    
    // Method to save the rendered PDF as an attachment.
    public PageReference saveAsPDF() {
    try {
        // Generate the PDF content
        PageReference pdfPage = Page.Estimate1;
        pdfPage.getParameters().put('id', estimate.Id);
        Blob pdfContent = pdfPage.getContentAsPDF();

        //unique file name
        String uniqueFileName = estimate.Name + '_Estimate_' + Datetime.now().format('yyyyMMddHHmmss') + '.pdf';

        ContentVersion contentVersion = new ContentVersion();
        contentVersion.Title = uniqueFileName;
        contentVersion.PathOnClient = uniqueFileName;
        contentVersion.VersionData = pdfContent; 
        insert contentVersion;

        // Fetch the ContentDocumentId for the new ContentVersion
        ContentDocument contentDocument = [
            SELECT Id 
            FROM ContentDocument 
            WHERE Id IN (SELECT ContentDocumentId FROM ContentVersion WHERE Id = :contentVersion.Id)
        ];

      
        List<ContentDocumentLink> existingLinks = [
            SELECT Id 
            FROM ContentDocumentLink 
            WHERE ContentDocumentId = :contentDocument.Id 
            AND LinkedEntityId = :estimate.Id
        ];

        if (existingLinks.isEmpty()) {
            ContentDocumentLink newLink = new ContentDocumentLink();
            newLink.ContentDocumentId = contentDocument.Id;
            newLink.LinkedEntityId = estimate.Id; // Link to the Estimate__c record
            newLink.ShareType = 'V'; // Viewer access
            newLink.Visibility = 'AllUsers';
            insert newLink;
        }

        // Add a success message
        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM, 'PDF saved successfully as ' + uniqueFileName + '!'));

    } catch (Exception e) {
        // Add an error message
        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Error saving PDF: ' + e.getMessage()));
    }
    return null; 
}



     /*   try{
            // Generate the PDF content
            PageReference pdfPage = Page.Estimate1;
            pdfPage.getParameters().put('id', estimate.Id);
            Blob pdfContent = pdfPage.getContentAsPDF();
            
            //Create an Attachement
            Attachment attachment = new Attachment();
            Attachment.ParentId = estimate.Id;
            Attachment.Name = estimate.Name + '_Estimate.pdf';
            Attachment.body = pdfContent;
            Attachment.ContentType = 'application/pdf';
            
            //save the attachemnt 
            insert attachment;
            
            //return a success message
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM, 'PDF saved successfully!'));
        }
        catch(Exception e){
            ApexPages.addMessage(new Apexpages.message(ApexPages.Severity.ERROR, 'Error saving PDF:' + e.getmessage()));
        }
        return ApexPages.currentPage(); // Stay on the same page
        }*/
    }