force-app/main/default/objects/Vendor__c/Vendor__c.object-meta.xml
<CustomObject>
    <label>Vendor</label>
    <nameField>
        <label>Vendor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendors</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vendor__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Vendors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VendorWO__c/VendorWO__c.object-meta.xml
<CustomObject>
    <label>VendorWO</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VendorWo</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VendorWO__c/fields/Related_Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Related_Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>Work_Order__c</referenceTo>
    <relationshipLabel>VendorWo</relationshipLabel>
    <relationshipName>VendorWo</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VendorWO__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Vendor__c</referenceTo>
    <relationshipLabel>VendorWo</relationshipLabel>
    <relationshipName>VendorWo</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/VendorWoTriggerHandler.cls
public class VendorWoTriggerHandler {
    public static void handleAfterInsert(List<VendorWo__c> newVendorWo) {
        List<VendorWO__c> vendorWithRelatedData = [
            SELECT Id, Vendor__c, Vendor__r.User__c, Vendor__r.User__r.Id, Related_Work_Order__c, CreatedBy.Profile.Name, CreatedById
            FROM VendorWO__c 
            WHERE Id IN :newVendorWo
        ];
        system.debug(vendorWithRelatedData);
        List<Work_Order__Share> sharesToCreate = new List<Work_Order__Share>();
        
        for (VendorWO__c vendor : vendorWithRelatedData) {
            // Share with brand user
            if (vendor.CreatedBy.Profile.Name == 'Brand Profile' && vendor.Related_Work_Order__c != null) {
                sharesToCreate.add(SharingHelper.createVendorShare(vendor.Related_Work_Order__c, vendor.Vendor__r.User__r.Id));
            }
            system.debug('sharing record'+ vendor.Vendor__r.User__r.Id);
                        system.debug('sharing related work order record'+ vendor.Related_Work_Order__c);

        }
        
        if (!sharesToCreate.isEmpty()) {
            Database.insert(sharesToCreate, false);
        }
    }
}