force-app/main/default/objects/Notification_Preference__c/Notification_Preference__c.object-meta.xml
<CustomObject>
    <label>Notification Preference</label>
    <nameField>
        <label>Notification Preference Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notification Preferences</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification_Preference__c/fields/Applicable_Profiles__c.field-meta.xml
<CustomField>
    <fullName>Applicable_Profiles__c</fullName>
    <label>Applicable Profiles</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>System Administrator</fullName>
            </value>
            <value>
                <fullName>FM - Brand user</fullName>
            </value>
            <value>
                <fullName>FM - Corporate User</fullName>
            </value>
            <value>
                <fullName>FM - Site user</fullName>
            </value>
            <value>
                <fullName>FM - Technician User</fullName>
            </value>
            <value>
                <fullName>FM - Vendor User</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Notification_Preference__c/fields/Email_Notification__c.field-meta.xml
<CustomField>
    <fullName>Email_Notification__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Email Notification</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Notification_Preference__c/fields/Push_Notification__c.field-meta.xml
<CustomField>
    <fullName>Push_Notification__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Push Notification</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User_Notification__c/User_Notification__c.object-meta.xml
<CustomObject>
    <label>User Notification</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>User_Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Notifications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Notification__c/fields/Is_Email_Notification__c.field-meta.xml
<CustomField>
    <fullName>Is_Email_Notification__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Email Notification</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User_Notification__c/fields/Notification_Preference__c.field-meta.xml
<CustomField>
    <fullName>Notification_Preference__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Notification Preference</label>
    <referenceTo>Notification_Preference__c</referenceTo>
    <relationshipLabel>User Notifications</relationshipLabel>
    <relationshipName>User_Notifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Notification__c/fields/Push_Notification__c.field-meta.xml
<CustomField>
    <fullName>Push_Notification__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Push Notification</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User_Notification__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User_Notifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/NotificationPreferenceController.cls
public with sharing class NotificationPreferenceController {
    @AuraEnabled(cacheable=true)
    public static List<Map<String, Object>> getPreferences() {
        //fetching the current user Id
        String userId = UserInfo.getUserId();
        // getting the current user profile name
        String userProfileName = [SELECT Profile.Name FROM User WHERE Id = :userId].Profile.Name;
        
        //nested query to get the user notification based on the current user and the notifcation available for the current user profile. 
        List<Notification_Preference__c> preferences = [
            SELECT Id, Name, Email_Notification__c, Push_Notification__c, Applicable_Profiles__c,
            (SELECT Notification_Preference__c, Is_Email_Notification__c, Push_Notification__c
             FROM User_Notifications__r
             WHERE User__c = :userId)
            FROM Notification_Preference__c
            WHERE Applicable_Profiles__c INCLUDES (:userProfileName)
        ];
        
        // the final map to store the result. 
        List<Map<String, Object>> result = new List<Map<String, Object>>();
        
        for (Notification_Preference__c pref : preferences) {
            
            //map to store the neccasary feidls of preference to filter user notification
            Map<String, Object> prefMap = new Map<String, Object>();
            prefMap.put('Id', pref.Id);
            prefMap.put('Name', pref.Name);
            
            if (!pref.User_Notifications__r.isEmpty()) {
                User_Notification__c userNotif = pref.User_Notifications__r[0];
                
                //if user notification is found pass the neccsary values from user notification to the component.
                prefMap.put('EmailNotificationEnabled', userNotif.Is_Email_Notification__c);
                prefMap.put('PushNotificationEnabled', userNotif.Push_Notification__c);
                
                // if no user notification record found pass the default values to the component.
            } else {
                System.debug('No User Notification Found for Preference. Using Default Values.');
                
                prefMap.put('EmailNotificationEnabled', pref.Email_Notification__c);
                prefMap.put('PushNotificationEnabled', pref.Push_Notification__c);
            }
            
            result.add(prefMap);
        }
        
        return result;
    }
    
    //method to create or update the user_notification__c record accordingly.
    @AuraEnabled
    public static void updatePreference(Id prefId, String type, Boolean enabled, Boolean emailValue, Boolean pushValue) {
        String userId = UserInfo.getUserId();
        String userProfileName = [SELECT Profile.Name FROM User WHERE Id = :userId].Profile.Name;
        
        
        List<User_Notification__c> existingNotifications = [
            SELECT Id, Is_Email_Notification__c, Push_Notification__c
            FROM User_Notification__c
            WHERE Notification_Preference__c = :prefId AND User__c = :userId
            LIMIT 1
        ];
        
        if (!existingNotifications.isEmpty()) {
            User_Notification__c existingNotification = existingNotifications[0];
            existingNotification.Is_Email_Notification__c = emailValue;
            existingNotification.Push_Notification__c = pushValue;
            update existingNotification;
        } else {
            User_Notification__c newNotification = new User_Notification__c();
            newNotification.Notification_Preference__c = prefId;
            newNotification.User__c = userId;
            newNotification.Profile__c = userProfileName;
            newNotification.Is_Email_Notification__c = emailValue;
            newNotification.Push_Notification__c = pushValue;
            insert newNotification;
        }
    }
}